### ISSUE TITLE
Version 0.32.6 seems to be broken

### ISSUE THREAD

**Issue by raviships** [Umkus/lambda-layer-sharp#29]
I tried to download the version 0.32.6 and use it in my layer, but it got an error.
downgrading the zip to 0.32.1 worked fine. So maybe there is a problem with this build?
I'm using node18.x with X86_64. and deploying it with the sst example app here: https://github.com/sst/sst/tree/master/examples/bucket-image-resize

My problem is already solved, so I wont be able to follow this issue.
Feel free to close it when solved.

**Comment by pstovik** [comment]
Version 0.32.6 seems to have issue on our project as well. 
Running CI tests via vitest (X64 architecture) are failing on "killed nodejs process", failure "the corrupted size vs. prev_size"
Version 0.32.1 with this in place https://sharp.pixelplumbing.com/install#worker-threads works

**Comment by DavidVaness** [comment]
Also using 0.32.1

**Comment by grant-d** [comment]
Ditto. Here is the error from lambda logs:

```
{
    "timestamp": "2024-02-15T21:57:18.474Z",
    "level": "ERROR",
    "message": {
        "errorType": "Error",
        "errorMessage": "Could not load the \"sharp\" module using the linux-arm64 runtime\nPossible solutions:\n- Ensure optional dependencies can be installed:\n    npm install --include=optional sharp\n    yarn add sharp --ignore-engines\n- Ensure your package manager supports multi-platform installation:\n    See https://sharp.pixelplumbing.com/install#cross-platform\n- Add platform-specific dependencies:\n    npm install --os=linux --cpu=arm64 sharp\n- Consult the installation documentation:\n    See https://sharp.pixelplumbing.com/install",
        "stackTrace": [
            "Error: Could not load the \"sharp\" module using the linux-arm64 runtime",
            "Possible solutions:",
            "- Ensure optional dependencies can be installed:",
            "    npm install --include=optional sharp",
            "    yarn add sharp --ignore-engines",
            "- Ensure your package manager supports multi-platform installation:",
            "    See https://sharp.pixelplumbing.com/install#cross-platform",
            "- Add platform-specific dependencies:",
            "    npm install --os=linux --cpu=arm64 sharp",
            "- Consult the installation documentation:",
            "    See https://sharp.pixelplumbing.com/install",
            "    at Object.257 (/opt/nodejs/node_modules/sharp/index.js:10119:9)",
            "    at __webpack_require__ (/opt/nodejs/node_modules/sharp/index.js:10447:41)",
            "    at Object.7300 (/opt/nodejs/node_modules/sharp/index.js:5406:1)",
            "    at __webpack_require__ (/opt/nodejs/node_modules/sharp/index.js:10447:41)",
            "    at Object.1842 (/opt/nodejs/node_modules/sharp/index.js:5854:15)",
            "    at __webpack_require__ (/opt/nodejs/node_modules/sharp/index.js:10447:41)",
            "    at /opt/nodejs/node_modules/sharp/index.js:10464:37",
            "    at Object.<anonymous> (/opt/nodejs/node_modules/sharp/index.js:10467:12)",
            "    at Module._compile (node:internal/modules/cjs/loader:1376:14)",
            "    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)"
        ]
    }
}
```

**Comment by omersimsek29** [comment]
Well I can confirm that I get the same error message as @grant-d  when trying to setup my lambda layer with version `0.32.6`, testing version `0.32.1` now.

**Comment by grant-d** [comment]
@omersimsek29 btw I never did figure it out, I have just stuck with the old version for now.
Hopefully someone else has a better idea

**Comment by CSilivestru** [comment]
Went through the same thing on SST -- running locally worked fine with 0.32.6 but production lambdas failed to build, even with specified architecture to arm64 and setting supported architecture explicitly both on the function and in pacakge.json.

@omersimsek29 I had to set the [supported architecture](https://pnpm.io/package_json#pnpmsupportedarchitectures) in my package json as well as on my function - similar to [here](https://pnpm.io/package_json#pnpmsupportedarchitectures) but swapping to x86_64 vs arm64.

Not sure if you're still having this issue or if that will help but thought I'd share :).

**Comment by robeberhardt** [comment]
anyone ever solve this? so many hours trying to build a sharp that works 😭

**Comment by omersimsek29** [comment]
Ehm, if I remember correctly my issue was that I specified the path and format wrong in my lambda layer, and also used the older version
