### ISSUE TITLE
Help with webpack

### ISSUE THREAD

**Issue by brandonregard** [Umkus/lambda-layer-sharp#30]
Using webpack (5.88.2) with your latest release (https://github.com/Umkus/lambda-layer-sharp/releases/download/0.32.6/sharp-layer.zip). 

I have created the layer using the zip referenced above and added to the Lambda that needs it. Source has been bundled with webpack.

Receiving the following: `Runtime.ImportModuleError: Error: Cannot find module 'sharp'`.

 I think it may have to do with the `externals` property used by webpack. I have followed the instructions from the sharp documentation: https://sharp.pixelplumbing.com/install#aws-lambda. Any experience here?

Here is the full CloudWatch log error:
```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'sharp'\nRequire stack:\n- /var/task/EventIotTriggerPreTraffic.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'sharp'",
        "Require stack:",
        "- /var/task/EventIotTriggerPreTraffic.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
```

**Comment by brandonregard** [comment]
Turned out to be an issue with `tsconfig.json` missing a `path` entry for `sharp`.
